<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <!-- Elemento raíz -->
    <xs:element name="estados">
        <xs:complexType>
            <xs:sequence>
                <!-- Uno o más elementos 'estado' -->
                <xs:element name="estado" maxOccurs="unbounded" minOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <!-- Descripción del estado -->
                            <xs:element name="estado_descripcion" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>