<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

  <!-- Elemento raíz -->
  <xs:element name="usuarios">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="usuario" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="usuario_id" type="xs:int"/>
              <xs:element name="usuario_nombre" type="xs:string"/>
              <xs:element name="usuario_apellido" type="xs:string"/>
              <xs:element name="usuario_usuario" type="xs:string"/>
              <xs:element name="usuario_telefono" minOccurs="1">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:pattern value="|[0-9]{9}"/> <!-- Vacío o 9 dígitos -->
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="usuario_email">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:pattern value="[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="usuario_clave" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>
